# -*- coding: utf-8 -*-
"""MLProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aXMpfydSYOGiQV3JXI__hCLCboNxrCeQ
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import MinMaxScaler
import lightgbm as lgb
from statsmodels.tsa.statespace.sarimax import SARIMAX
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping
#from google.colab import drive
#drive.mount('/content/drive')

DATA_PATH = r"C:\Users\user\Downloads\Machin Learning Project\yidu"


train = pd.read_csv(DATA_PATH + "\\train.csv", parse_dates=["date"])
test = pd.read_csv(DATA_PATH + "\\test.csv", parse_dates=["date"])
print(train.shape)
print(train.head())

counts = (
    train.groupby(["store", "item"])
         .size()
         .reset_index(name="rows")
         .sort_values("rows", ascending=False)
)
counts.head()

store_id = int(counts.iloc[0]["store"])
item_id  = int(counts.iloc[0]["item"])
print("Using store:", store_id, "item:", item_id)

series_data = train[
    (train["store"] == store_id) &
    (train["item"] == item_id)
].sort_values("date")
print("Rows before features:", len(series_data))

def feature_engineering(df):
    df = df.copy()
    df["dayofweek"] = df["date"].dt.dayofweek
    df["month"] = df["date"].dt.month
    for lag in [1, 7, 14]:
        df[f"lag_{lag}"] = df["sales"].shift(lag)
    df["rolling_mean_7"] = df["sales"].shift(1).rolling(7).mean()
    return df
series_data = feature_engineering(series_data)
series_data = series_data.dropna()
print("Rows after features:", len(series_data))

split = int(len(series_data) * 0.8)
train_data = series_data.iloc[:split]
test_data  = series_data.iloc[split:]
print("Train:", len(train_data))
print("Test :", len(test_data))

FEATURES = [
    "dayofweek", "month",
    "lag_1", "lag_7", "lag_14",
    "rolling_mean_7"
]
X_train = train_data[FEATURES]
y_train = train_data["sales"]
X_test = test_data[FEATURES]
y_test = test_data["sales"]
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

rf = RandomForestRegressor(
    n_estimators=200,
    max_depth=10,
    random_state=42
)

rf.fit(X_train, y_train)
rf_preds = rf.predict(X_test)
print("RF training successful ✅")

rmse = np.sqrt(mean_squared_error(y_test, rf_preds))
mae  = mean_absolute_error(y_test, rf_preds)
print("RMSE:", rmse)
print("MAE :", mae)

import numpy as np
from sklearn.metrics import mean_squared_error, mean_absolute_error

def evaluate(y_true, y_pred, model_name):
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    mae  = mean_absolute_error(y_true, y_pred)
    mape = np.mean(np.abs((y_true - y_pred) / y_true)) * 100
    print(f"\n{model_name} Performance")
    print(f"RMSE : {rmse:.2f}")
    print(f"MAE  : {mae:.2f}")
    print(f"MAPE : {mape:.2f}%")

rf = RandomForestRegressor(
    n_estimators=200,
    max_depth=15,
    random_state=42,
    n_jobs=-1
)
rf.fit(X_train, y_train)
rf_preds = rf.predict(X_test)
evaluate(y_test, rf_preds, "Random Forest")

import matplotlib.pyplot as plt

plt.figure(figsize=(10,4))
plt.plot(y_test.values[:200], label="Actual")
plt.plot(rf_preds[:200], label="Predicted")
plt.title("Random Forest – Actual vs Predicted Sales")
plt.legend()
plt.show()

import lightgbm as lgb
lgb_model = lgb.LGBMRegressor(
    n_estimators=400,
    learning_rate=0.05,
    max_depth=8,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)
lgb_model.fit(X_train, y_train)
lgb_preds = lgb_model.predict(X_test)
evaluate(y_test, lgb_preds, "LightGBM")

plt.figure(figsize=(8,4))
lgb.plot_importance(lgb_model, max_num_features=10)
plt.title("LightGBM Feature Importance")
plt.show()

from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
from tensorflow.keras.callbacks import EarlyStopping
scaler = MinMaxScaler()
scaled_sales = scaler.fit_transform(series_data[["sales"]])
def create_sequences(data, window=14):
    X, y = [], []
    for i in range(window, len(data)):
        X.append(data[i-window:i, 0])
        y.append(data[i, 0])
    return np.array(X), np.array(y)
X_seq, y_seq = create_sequences(scaled_sales)
split = int(len(X_seq) * 0.8)
X_train_lstm = X_seq[:split]
X_test_lstm  = X_seq[split:]
y_train_lstm = y_seq[:split]
y_test_lstm  = y_seq[split:]
X_train_lstm = X_train_lstm.reshape((X_train_lstm.shape[0], X_train_lstm.shape[1], 1))
X_test_lstm  = X_test_lstm.reshape((X_test_lstm.shape[0], X_test_lstm.shape[1], 1))

lstm = Sequential([
    LSTM(64, return_sequences=True, input_shape=(X_train_lstm.shape[1], 1)),
    LSTM(32),
    Dense(1)
])
lstm.compile(optimizer="adam", loss="mse")
lstm.fit(
    X_train_lstm, y_train_lstm,
    epochs=10,
    batch_size=32,
    validation_split=0.2,
    callbacks=[EarlyStopping(patience=3)],
    verbose=1
)

lstm_preds_scaled = lstm.predict(X_test_lstm)
lstm_preds = scaler.inverse_transform(lstm_preds_scaled)
y_test_lstm_inv = scaler.inverse_transform(y_test_lstm.reshape(-1,1))
evaluate(y_test_lstm_inv.flatten(), lstm_preds.flatten(), "LSTM")

# LightGBM
train_preds_lgb = lgb_model.predict(X_train)
residuals = y_train.values - train_preds_lgb
residuals_scaled = scaler.fit_transform(residuals.reshape(-1,1))
X_res, y_res = create_sequences(residuals_scaled, window=14)
X_res = X_res.reshape((X_res.shape[0], X_res.shape[1], 1))
lstm.fit(X_res, y_res, epochs=5, batch_size=32, verbose=0)

# Calculate hybrid predictions as the average of the predictions from RF, LightGBM, and LSTM
hybrid_preds = (rf_preds[:len(lstm_preds.flatten())] + lgb_preds[:len(lstm_preds.flatten())] + lstm_preds.flatten()) / 3

evaluate(y_test.values[:len(lstm_preds.flatten())], hybrid_preds, "Hybrid LightGBM + LSTM")

results = pd.DataFrame({
    "Model": ["Random Forest", "LightGBM", "LSTM", "Hybrid"],
    "RMSE": [
        np.sqrt(mean_squared_error(y_test, rf_preds)),
        np.sqrt(mean_squared_error(y_test, lgb_preds)),
        np.sqrt(mean_squared_error(y_test_lstm_inv.flatten(), lstm_preds.flatten())),
        np.sqrt(mean_squared_error(y_test[:len(hybrid_preds)], hybrid_preds))
    ]
})

results

results_table = pd.DataFrame({
    "Model": ["Random Forest", "LightGBM", "LSTM", "Hybrid"],
    "MAE": [
        mean_absolute_error(y_test, rf_preds),
        mean_absolute_error(y_test, lgb_preds),
        mean_absolute_error(y_test_lstm_inv.flatten(), lstm_preds.flatten()),
        mean_absolute_error(y_test[:len(hybrid_preds)], hybrid_preds)
    ]
})

results_table

plt.figure(figsize=(8,4))
plt.bar(results["Model"], results["RMSE"])
plt.title("RMSE Comparison Across Forecasting Models")
plt.ylabel("RMSE")
plt.grid(axis="y")
plt.show()

plt.figure(figsize=(8,4))
plt.bar(results_table["Model"], results_table["MAE"])
plt.title("MAE Comparison Across Forecasting Models")
plt.ylabel("MAE")
plt.grid(axis="y")
plt.show()

plt.figure(figsize=(8,4))
plt.bar(results["Model"], results["RMSE"])
plt.title("RMSE Comparison Across Forecasting Models")
plt.ylabel("RMSE")
plt.grid(axis="y")
plt.show()

plt.figure(figsize=(8,4))
plt.bar(results["Model"], results["RMSE"])
plt.title("RMSE Comparison Across Forecasting Models")
plt.ylabel("RMSE")
plt.grid(axis="y")
plt.show()

plt.figure(figsize=(8,4))
plt.bar(results["Model"], results["RMSE"])
plt.title("RMSE Comparison Across Forecasting Models")
plt.ylabel("RMSE")
plt.grid(axis="y")
plt.show()

plt.figure(figsize=(12,5))
plt.plot(y_test.values[:150], label="Actual", linewidth=3)
plt.plot(rf_preds[:150], label="Random Forest")
plt.plot(lgb_preds[:150], label="LightGBM")
plt.plot(hybrid_preds[:150], label="Hybrid")
plt.plot(
    lstm_preds.flatten()[:150],
    label="LSTM",
    linestyle="--"
)
plt.title("Actual vs Predicted Sales – Model Comparison")
plt.xlabel("Time")
plt.ylabel("Sales Units")
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(10,4))
plt.plot(np.cumsum(np.abs(y_test - rf_preds)), label="RF")
plt.plot(np.cumsum(np.abs(y_test - lgb_preds)), label="LightGBM")
# Convert to numpy arrays
y_true = y_test.values
y_pred = np.array(hybrid_preds)

# Align lengths (important for LSTM-based models)
min_len = min(len(y_true), len(y_pred))
y_true = y_true[-min_len:]
y_pred = y_pred[-min_len:]

# Plot cumulative absolute error
plt.plot(
    np.cumsum(np.abs(y_true - y_pred)),
    label="Hybrid"
)

#plt.plot(np.cumsum(np.abs(y_test.values - np.array(hybrid_preds))),
    #label="Hybrid")

#plt.plot(np.cumsum(np.abs(y_test - hybrid_preds)), label="Hybrid")
plt.title("Cumulative Absolute Error Over Time")
plt.xlabel("Time")
plt.ylabel("Cumulative Error")
plt.legend()
plt.show()

# Install ipywidgets if not already installed
#!pip install ipywidgets

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from ipywidgets import interact, IntSlider, Dropdown

# Load data
#DATA_PATH = "/content/drive/MyDrive/yidu/"
from pathlib import Path

DATA_PATH = Path(r"C:\Users\user\Downloads\Machin Learning Project\yidu")
train = pd.read_csv(DATA_PATH / "train.csv", parse_dates=["date"])

#train = pd.read_csv(DATA_PATH + "\\train.csv", parse_dates=["date"])

# Unique stores and items
stores = train["store"].unique()
items  = train["item"].unique()

# Simulated predictions for demo
def simulate_predictions(series):
    n = len(series)
    rf = series * np.random.uniform(0.95, 1.05, n)
    lgb = series * np.random.uniform(0.9, 1.1, n)
    lstm = series * np.random.uniform(0.85, 1.15, n)
    hybrid = (rf + lgb + lstm) / 3
    return rf, lgb, lstm, hybrid

# Function to update plot
def plot_forecast(store_id, item_id, window=14):
    series_data = train[(train["store"]==store_id) & (train["item"]==item_id)].sort_values("date")
    series = series_data["sales"].values[-200:]  # last 200 points for visualization
    rf, lgb, lstm, hybrid = simulate_predictions(series)

    plt.figure(figsize=(12,5))
    plt.plot(series, label="Actual", linewidth=2)
    plt.plot(rf, label="Random Forest")
    plt.plot(lgb, label="LightGBM")
    plt.plot(lstm, label="LSTM", linestyle="--")
    plt.plot(hybrid, label="Hybrid", linestyle="-.")
    plt.title(f"Store {store_id}, Item {item_id} – Forecast (Window={window})")
    plt.xlabel("Time")
    plt.ylabel("Sales Units")
    plt.legend()
    plt.grid(True)
    plt.show()

# Interactive widgets
interact(plot_forecast,
         store_id=Dropdown(options=stores, description="Store ID"),
         item_id=Dropdown(options=items, description="Item ID"),
         window=IntSlider(min=7, max=30, step=1, value=14, description="Forecast Window"));